[build]
  command = "npm install"

[[edge_functions]]
  # This Edge function acts as a firewall for all requests to the NAS.
  # If the user doesn't have the 'calite_auth' cookie, it rejects them back to the welcome screen.
  path = "/tos/*"
  function = "protect-tos"

[[redirects]]
  # Proxy ALL traffic to the TerraMaster NAS
  # "force = false" means it will serve index.html and dashboard.html locally if requested,
  # but anything else (like the TerraMaster /js/ or /css/ files) gets fetched from the NAS!
  from = "/*"
  to = "http://172.222.155.52:8181/:splat"
  status = 200
  force = false
