# Netlify configuration file

[build]
  # We need to run npm install so Netlify pulls the @netlify/blobs library before deploying
  command = "npm install"

[[redirects]]
  # Safely allow traffic to the proxy (172.222.155.52 NAS)
  from = "/tos/*"
  to = "http://172.222.155.52:8181/tos/:splat"
  status = 200
  force = true

# The root "/" will automatically serve `index.html` (The Welcome Screen)
# "/dashboard.html" will automatically serve the dashboard
# "/.netlify/functions/*" will automatically serve your serverless API
